trigger:
  - master
  - refs/tags/*

pr:
  - master
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  PRE_RESTORE_PROJECTS: true  # Windows is having an issue on CI right now
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      areaPath: 'DevDiv\Xamarin SDK\Android'
      preBuildSteps:
        - pwsh: |
            dotnet tool install --global boots
            boots https://aka.ms/xamarin-android-commercial-d16-5-macos
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool install --global boots
            boots https://aka.ms/xamarin-android-commercial-d16-5-windows
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '0.4.2'
        - 'xamarin.androidx.migration.tool': '1.0.0-rc1'
      postBuildSteps:
        - pwsh: .\fatten.ps1
          displayName: 'Fatten the NuGet packages'
        # Run some internal auditing on Windows
        - ${{ if and(eq(variables['System.TeamProject'], 'devdiv'), eq(variables['System.JobName'], 'windows')) }}:
          - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
            condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
            displayName: Component Detection - Log
            inputs:
              scanType: LogOnly
          - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
            displayName: Component Detection - Report
          - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
            condition: eq(variables['System.TeamProject'], 'devdiv')
            displayName: 'PoliCheck'
            inputs:
              targetType: F
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v1.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
